modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/newtykins/secmmwl/issues"

[[mods]]
modId="secmmwl" #mandatory
version="${file.jarVersion}"
displayName="Super Epic Cool Minecraft Mod (With Lasers)"
# updateJSONURL="http://myurl.me/"
# displayURL="http://example.com/"
# logoFile="examplemod.png"
credits="Created by newt and NTB"
authors="newt, NTB"

description='''
A very super epic cool minecraft mod. Yes, it has lasers.
'''

[[dependencies.secmmwl]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.secmmwl]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
